### ISSUE TITLE
dependency conflict

### ISSUE THREAD

**Issue by kittani** [ulbmuenster/invenio-dnb-urn#1]
I am using Invenio version 11, and trying to add URN DNB. I am following this documentation:
https://inveniordm.docs.cern.ch/customize/other-pids/urns/
I added the following line into the pip file:
invenio-dnb-urn = ">=0.1.3,<1.0.0"
and then deleted the pipfile.lock
after running the: invenio-cli install, I got this packages conflict error:

      CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Cannot install -r /tmp/pipenv0ewfai37requirements/ pipenv-sflotksc-constraints.txt (line 2) and invenio-app-rdm[opensearch2,postgresql]==11.0.0 because these package versions have conflicting dependencies.

Could anyone help me with this issue @wgresshoff ?

**Comment by wgresshoff** [comment]
Hi @kittani , sorry I'm currently on vacation. This was developed for an early v12 development version. Should Work with v11 when you patch in setup.cfg the dependency to invenio-rdm-records to >=1.3.6, <2.0.0
Remember this ist an Alpha Version and was never used in production!

**Comment by kittani** [comment]
Hi @wgresshoff , Thank you for your reply. I tried your suggested solution, but it gives me the following error:

    CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Cannot install -r /tmp/pipenv3k41sivurequirements/pipenv-vura5p40-constraints.txt (line 4), invenio-app-rdm[opensearch2,postgresql]==11.0.0 and invenio-rdm-records<2.0.0 and >=1.3.6 because these package versions have conflicting dependencies.

**Comment by kittani** [comment]
After that error, I tried this:
I updated the invenio-app-rdm to this (before, it was exactly version 11):

    invenio-app-rdm = {extras = ["postgresql", "opensearch2"], version = ">=11.0.0,<12.0.0"}

It gives me the following error:

    CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Cannot install -r /tmp/pipenv9kch0dr3requirements/pipenv-
    _drz_djp-constraints.txt (line 19) and dnb-urn-service>=0.1.3 because these package versions have 
    conflicting dependencies.

So, how to deal with the version of dnb-urn-service?

**Comment by wgresshoff** [comment]
What ist the content of the mentioned pipenv*constraints.txt files? This is the file which produces the conflict.

**Comment by kittani** [comment]
I don't know what is this file and how to find it

**Comment by wgresshoff** [comment]
_ts in your error message: `/tmp/pipenv9kch0dr3requirements/pipenv-
_drz_djp-constraints.txt`

**Comment by kittani** [comment]
Yes, I know. But I searched for it and couldn't find it

**Comment by wgresshoff** [comment]
Hm, without any further additional messages I fear I can't help. We don't run any InvenioRDM v11 here any longer (we don't have enough developers), so we have just the information you can provide.
You somehave have to reconfigure, so the files in /tmp are not deleted directly.

**Comment by kittani** [comment]
Thank you for your help. 
I am trying it in V12. I hope that it will work

**Comment by kittani** [comment]
@wgresshoff I have a question, please. Which invenio version are you using?

**Comment by wgresshoff** [comment]
I'm currently using a development version of v12 (v12.b3.dev6 actually) but didn't try so far to include the urn module. As there are current discussions on PID topics (regarding DOI and parent DOI) which might influence the implementation of the urn module as well I will have a look at the urn module this week.

**Comment by wgresshoff** [comment]
@kittani Just one question: did you install the module from pypi or did you install from git? Might be a good idea to try from git, because I'm not sure I generated the package correctly. Never tried to install from pypi.

**Comment by kittani** [comment]
I tried to install it using pypi.
I will try git. Thank you for the advice

**Comment by wgresshoff** [comment]
It should now be possible to install from Pypi.org without the dependency conflict. This is a version which should work with v11 but not with v12 (I will look into that next week), you should insert
invenio-dnb-urn = ">=0.2.2,<1.0.0"
to your Pipfile instead of the original line in the docs.

**Comment by kittani** [comment]
thank you @wgresshoff for your support. I will try it and hope that everything goes well
